apiVersion: apps/v1

kind: Deployment

metadata:

  labels:

    app: service-image-recognition

  name: service-image-recognition

spec:

  replicas: 1

  selector:

    matchLabels:

      app: service-image-recognition

  template:

    metadata:

      labels:

        app: service-image-recognition

    spec:

      containers:

        - name: service-image-recognition

          image: quay.io/lordofthejars/flask-app:1.0.0

          ports:

            - containerPort: 8080

---

apiVersion: v1

kind: Service

metadata:

  name: service-image-recognition

  labels:

    app: service-image-recognition

spec:

  ports:

    - name: http

      port: 8080

  selector:

    app: service-image-recognition

  type: LoadBalancer